#!/usr/bin/env bash
set -euo pipefail

install_ohmyzsh() {
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

symlink_zsh_config() {
  rm ~/.zshrc || true
  ln -s $(pwd)/.zshrc ~/.zshrc
}

symlink_vscode_config() {
  rm $HOME/Library/Application\ Support/Code/User/settings.json
  ln -s $(pwd)/vscode.json $HOME/Library/Application\ Support/Code/User/settings.json
}

install() {
  # ohmyzsh
  if [[ ! $ZSH ]]; then install_ohmyzsh; fi
  symlink_zsh_config
  symlink_vscode_config
}

install
